name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Pobranie kodu
        uses: actions/checkout@v3

      - name: Konfiguracja Pythona
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalacja zależności
        run: |
          pip install -r requirements.txt
          pip install flake8

      - name: Analiza kodu (Flake8)
        run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: Uruchomienie testów (pytest)
        run: pytest

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Pobranie kodu
        uses: actions/checkout@v3

      - name: Logowanie do Docker Hub-a
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Budowanie obrazu
        uses: docker/build-push-action@v4
        with:
          context: .
          load: true
          tags: ${{ secrets.DOCKER_USERNAME }}/moje-api:latest

      - name: Skanowanie bezpieczeństwa
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ secrets.DOCKER_USERNAME }}/moje-api:latest'
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Wypchnięcie przetestowanego obrazu na Docker Hub-a
        run: docker push ${{ secrets.DOCKER_USERNAME }}/moje-api:latest

      - name: Wdrożenie na Render
        run: curl -f ${{ secrets.RENDER_DEPLOY_HOOK }}